import = ["~/.config/alacritty/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Maple Mono NF"
# family = "Iosevka Term SS14"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
# family = "Iosevka Term SS14"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
# family = "Iosevka Term SS14"
style = "Italic"

[font.normal]
# family = "Iosevka Term SS14"
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
opacity = 0.97
blur = true
dynamic_padding = true

# [window.dimensions]
# columns = 100
# lines = 30
